# Generated by Django 6.0 on 2026-03-17 07:16

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('permission_version', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.TextField(help_text='URL-friendly identifier', unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('insane', 'Insane')], db_index=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('gitlab', 'GitLab')], default='manual', max_length=20)),
                ('storage_path', models.TextField(help_text='Đường dẫn lưu trữ file challenge')),
                ('gitlab_path', models.TextField(blank=True, help_text='Đường dẫn GitLab nếu source là gitlab', null=True)),
                ('challenge_point', models.IntegerField(default=0)),
                ('instance_required', models.BooleanField(default=False, help_text='Challenge có cần instance để chạy không')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.TextField(help_text='Tiêu đề bài học')),
                ('lesson_type', models.CharField(choices=[('markdown', 'Markdown'), ('video', 'Video'), ('miniquiz', 'Mini Quiz')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('outline', 'Outline')], default='manual', max_length=20)),
                ('content_md', models.TextField(blank=True, help_text='Nội dung markdown', null=True)),
                ('video_url', models.TextField(blank=True, help_text='URL video', null=True)),
                ('video_duration', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('learning_point', models.IntegerField(default=0)),
                ('learning_time', models.IntegerField(blank=True, help_text='Thời gian học (phút)', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='UserPermissionCache',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permission_cache', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('encoded_permissions', models.TextField(help_text='Base64 encoded permission bitmap')),
                ('permission_version', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_permission_cache',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('api', 'API')], max_length=20)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_username', models.TextField(blank=True, null=True)),
                ('aggregate_type', models.CharField(choices=[('user', 'User'), ('course', 'Course'), ('lesson', 'Lesson'), ('challenge', 'Challenge'), ('quiz', 'Quiz'), ('permission', 'Permission'), ('role', 'Role'), ('system', 'System')], max_length=20)),
                ('aggregate_id', models.BigIntegerField()),
                ('action', models.TextField(help_text="Action performed (e.g., 'create', 'update', 'delete')")),
                ('metadata', models.JSONField(blank=True, help_text='Additional context (changed fields, old/new values, etc.)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['actor_type', 'actor_id'], name='audit_log_actor_t_16ca8a_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='audit_log_aggrega_984cea_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeGitlab',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('challenge', models.OneToOneField(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gitlab_info', serialize=False, to='api.challenge')),
                ('project_id', models.BigIntegerField()),
                ('project_url', models.TextField()),
                ('default_branch', models.TextField(default='main')),
                ('last_commit_sha', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'challenge_gitlab',
            },
        ),
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Category',
                'verbose_name_plural': 'Challenge Categories',
                'db_table': 'challenge_category',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='api.challengecategory'),
        ),
        migrations.CreateModel(
            name='ChallengeFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('flag_value', models.TextField(help_text='Hashed flag value for security')),
                ('is_case_sensitive', models.BooleanField(default=True)),
                ('is_regex', models.BooleanField(default=False)),
                ('random_tail_length', models.IntegerField(default=0, help_text='Độ dài phần random cho instance-specific flags')),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='api.challenge')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_flag',
            },
        ),
        migrations.CreateModel(
            name='ChallengeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('instance_info', models.JSONField(blank=True, help_text='Thông tin instance (IP, port, etc.)', null=True)),
                ('flag_value', models.TextField(blank=True, help_text='Hashed flag value cho instance này (nếu random)', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated')], default='running', max_length=20)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Thời gian hết hạn instance (TTL do admin cấu hình)', null=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.challenge')),
                ('challenge_flag', models.ForeignKey(blank=True, db_column='challenge_flag_id', help_text='Flag template dùng để tạo flag cho instance này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='api.challengeflag')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_instance',
            },
        ),
        migrations.CreateModel(
            name='ChallengeInstanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('log_message', models.TextField()),
                ('challenge_instance', models.ForeignKey(db_column='challenge_instance_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.challengeinstance')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_instance_log',
                'ordering': ['-log_time'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_item', models.BooleanField(default=False, help_text='True nếu là item (challenge/lesson/quiz), False nếu là folder')),
                ('title', models.TextField()),
                ('path', models.TextField(db_index=True, default='', help_text='Dot-separated ancestor IDs (ví dụ: 1.3)')),
                ('position', models.IntegerField(default=0, help_text='Thứ tự hiển thị trong cùng parent')),
                ('challenge', models.OneToOneField(blank=True, db_column='challenge_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='api.challenge')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.challengenode')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_node',
            },
        ),
        migrations.CreateModel(
            name='ChallengeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Tag',
                'verbose_name_plural': 'Challenge Tags',
                'db_table': 'challenge_tag',
            },
        ),
        migrations.CreateModel(
            name='ChallengeTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='tag_mappings', to='api.challenge')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_mappings', to='api.challengetag')),
            ],
            options={
                'db_table': 'challenge_tag_map',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('estimated_time', models.IntegerField(blank=True, help_text='Thời gian ước lượng (phút)', null=True)),
                ('learning_point', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.coursecategory')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Tag',
                'verbose_name_plural': 'Course Tags',
                'db_table': 'course_tag',
            },
        ),
        migrations.CreateModel(
            name='CourseTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='tag_mappings', to='api.course')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='api.coursetag')),
            ],
            options={
                'db_table': 'course_tag_map',
            },
        ),
        migrations.CreateModel(
            name='LessonOutline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lesson', models.OneToOneField(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='outline_info', serialize=False, to='api.lesson')),
                ('outline_doc_id', models.TextField(unique=True)),
                ('outline_url', models.TextField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_outline',
            },
        ),
        migrations.CreateModel(
            name='CourseNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_item', models.BooleanField(default=False, help_text='True nếu là item (challenge/lesson/quiz), False nếu là folder')),
                ('title', models.TextField()),
                ('path', models.TextField(db_index=True, default='', help_text='Dot-separated ancestor IDs (ví dụ: 1.3)')),
                ('position', models.IntegerField(default=0, help_text='Thứ tự hiển thị trong cùng parent')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.course')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.coursenode')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.OneToOneField(blank=True, db_column='lesson_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='api.lesson')),
            ],
            options={
                'db_table': 'course_node',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('achievement', 'Achievement'), ('course', 'Course'), ('challenge', 'Challenge'), ('quiz', 'Quiz')], max_length=20)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Additional data (links, ids, etc.)', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_broadcast', models.BooleanField(default=False, help_text='If True, sent to all users')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', help_text='NULL for broadcast notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Synced by startup endpoint scan')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Category',
                'verbose_name_plural': 'Quiz Categories',
                'db_table': 'quiz_category',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('quiz_point', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0, help_text='Denormalized: keep in sync with COUNT(quiz_question) via Django signal')),
                ('time_limit_sec', models.IntegerField(blank=True, help_text='Giới hạn thời gian (giây)', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='api.quizcategory')),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('total_questions', models.IntegerField(blank=True, help_text='Số câu lấy ra', null=True)),
                ('time_limit_sec', models.IntegerField(blank=True, help_text='Thời gian làm bài (giây)', null=True)),
                ('random_question', models.BooleanField(default=True)),
                ('random_option', models.BooleanField(default=True)),
                ('allow_review', models.BooleanField(default=True)),
                ('allow_retry', models.BooleanField(default=True)),
                ('max_attempt', models.IntegerField(blank=True, help_text='Số lần làm tối đa (NULL = unlimited)', null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.quiz')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_config',
            },
        ),
        migrations.CreateModel(
            name='QuizNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_item', models.BooleanField(default=False, help_text='True nếu là item (challenge/lesson/quiz), False nếu là folder')),
                ('title', models.TextField()),
                ('path', models.TextField(db_index=True, default='', help_text='Dot-separated ancestor IDs (ví dụ: 1.3)')),
                ('position', models.IntegerField(default=0, help_text='Thứ tự hiển thị trong cùng parent')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.quiznode')),
                ('quiz', models.OneToOneField(blank=True, db_column='quiz_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='api.quiz')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_node',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('content', models.JSONField(help_text='Nội dung câu hỏi (JSON)')),
                ('explanation', models.TextField(blank=True, help_text='Giải thích đáp án', null=True)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=1)),
                ('position', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_question',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(default=0, help_text='Thứ tự câu hỏi trong lesson miniquiz')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='api.lesson')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mappings', to='api.quizquestion')),
            ],
            options={
                'db_table': 'lesson_question',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('answer', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizquestion')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_question_answer',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.quizquestion')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_question_option',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Tag',
                'verbose_name_plural': 'Quiz Tags',
                'db_table': 'quiz_tag',
            },
        ),
        migrations.CreateModel(
            name='QuizTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='tag_mappings', to='api.quiz')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mappings', to='api.quiztag')),
            ],
            options={
                'db_table': 'quiz_tag_map',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='api.permission')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='api.role')),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('value_type', models.CharField(choices=[('bool', 'Bool'), ('int', 'Int'), ('string', 'String'), ('json', 'JSON'), ('secret', 'Secret')], default='string', max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True, help_text='If False, system-managed; API PATCH returns 403')),
                ('is_runtime', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='UserAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('provider', models.CharField(choices=[('authentik', 'Authentik'), ('google', 'Google'), ('github', 'GitHub')], max_length=20)),
                ('external_id', models.TextField()),
                ('extra_data', models.JSONField(blank=True, help_text='Additional data from provider', null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auth_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_identity',
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='api.challenge')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_challenge_progress',
            },
        ),
        migrations.CreateModel(
            name='UserChallengeSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('submitted_flag', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_submits', to='api.challenge')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_challenge_submit',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='api.course')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_course_progress',
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='api.lesson')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='api.permission')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_permission',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entry_year', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='vi', max_length=10)),
                ('theme', models.CharField(default='system', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('total_learning_point', models.IntegerField(default=0)),
                ('total_challenge_point', models.IntegerField(default=0)),
                ('total_quiz_point', models.IntegerField(default=0)),
                ('course_completed', models.IntegerField(default=0)),
                ('challenge_completed', models.IntegerField(default=0)),
                ('quiz_completed', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('config', models.JSONField(blank=True, help_text='Cấu hình quiz (số câu, random, thời gian/câu...)', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='api.quiz')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quiz_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('answer_data', models.JSONField(help_text='Dữ liệu câu trả lời (option id, text...)')),
                ('score_obtained', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.quizquestion')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.userquizattempt')),
            ],
            options={
                'db_table': 'user_quiz_answer',
            },
        ),
        migrations.CreateModel(
            name='UserQuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('best_score', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='api.quiz')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quiz_progress',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('refresh_token_hash', models.TextField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, db_column='revoked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddField(
            model_name='challengegitlab',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengegitlab',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['slug'], name='challenge_slug_83f6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['title'], name='challenge_title_a63bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['category'], name='challenge_categor_1cddb0_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status'], name='challenge_status_eaa511_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['difficulty'], name='challenge_difficu_1f6034_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['source'], name='challenge_source_05234b_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeflag',
            index=models.Index(fields=['challenge'], name='challenge_f_challen_d0abf9_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['challenge'], name='challenge_i_challen_e4c1da_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['user'], name='challenge_i_user_id_d25694_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['user', 'challenge'], name='challenge_i_user_id_903f17_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengeinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('user', 'challenge'), name='uq_challenge_instance_active'),
        ),
        migrations.AddIndex(
            model_name='challengeinstancelog',
            index=models.Index(fields=['challenge_instance'], name='challenge_i_challen_5bf4df_idx'),
        ),
        migrations.AddIndex(
            model_name='challengenode',
            index=models.Index(fields=['parent'], name='challenge_n_parent__f063a7_idx'),
        ),
        migrations.AddIndex(
            model_name='challengenode',
            index=models.Index(fields=['challenge'], name='challenge_n_challen_6d09a3_idx'),
        ),
        migrations.AddIndex(
            model_name='challengenode',
            index=models.Index(fields=['path'], name='challenge_n_path_c8f381_idx'),
        ),
        migrations.AddIndex(
            model_name='challengetagmap',
            index=models.Index(fields=['challenge'], name='challenge_t_challen_ed13fe_idx'),
        ),
        migrations.AddIndex(
            model_name='challengetagmap',
            index=models.Index(fields=['tag'], name='challenge_t_tag_id_836194_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengetagmap',
            unique_together={('challenge', 'tag')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='course_categor_16662e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetagmap',
            index=models.Index(fields=['course'], name='course_tag__course__e2222b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetagmap',
            index=models.Index(fields=['tag'], name='course_tag__tag_id_d74703_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetagmap',
            unique_together={('course', 'tag')},
        ),
        migrations.AddField(
            model_name='lessonoutline',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonoutline',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coursenode',
            index=models.Index(fields=['course'], name='course_node_course__0c89cb_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenode',
            index=models.Index(fields=['parent'], name='course_node_parent__088b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenode',
            index=models.Index(fields=['lesson'], name='course_node_lesson__e41b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenode',
            index=models.Index(fields=['is_item'], name='course_node_is_item_37144c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenode',
            index=models.Index(fields=['path'], name='course_node_path_e28ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_366c29_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_8a483f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_broadcast'], name='notificatio_is_broa_c35fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['name'], name='permission_name_fa4988_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_active'], name='permission_is_acti_50c675_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['category'], name='quiz_categor_932911_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status'], name='quiz_status_ab1832_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['title'], name='quiz_title_411aea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizconfig',
            unique_together={('quiz', 'user')},
        ),
        migrations.AddIndex(
            model_name='quiznode',
            index=models.Index(fields=['parent'], name='quiz_node_parent__6dbe08_idx'),
        ),
        migrations.AddIndex(
            model_name='quiznode',
            index=models.Index(fields=['quiz'], name='quiz_node_quiz_id_2e68ad_idx'),
        ),
        migrations.AddIndex(
            model_name='quiznode',
            index=models.Index(fields=['path'], name='quiz_node_path_4f37d9_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz'], name='quiz_questi_quiz_id_57d9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonquestion',
            index=models.Index(fields=['lesson'], name='lesson_ques_lesson__a81bad_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonquestion',
            index=models.Index(fields=['question'], name='lesson_ques_questio_dc08e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonquestion',
            unique_together={('lesson', 'question')},
        ),
        migrations.AddIndex(
            model_name='quizquestionanswer',
            index=models.Index(fields=['question'], name='quiz_questi_questio_68ee9a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestionoption',
            index=models.Index(fields=['question'], name='quiz_questi_questio_9c88fa_idx'),
        ),
        migrations.AddIndex(
            model_name='quiztagmap',
            index=models.Index(fields=['quiz'], name='quiz_tag_ma_quiz_id_d3a72b_idx'),
        ),
        migrations.AddIndex(
            model_name='quiztagmap',
            index=models.Index(fields=['tag'], name='quiz_tag_ma_tag_id_8e513a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quiztagmap',
            unique_together={('quiz', 'tag')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='role_name_796487_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='role_permis_role_id_92d8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='role_permis_permiss_9dac09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['key'], name='system_conf_key_850519_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthprovider',
            index=models.Index(fields=['user'], name='user_identi_user_id_d5657f_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthprovider',
            index=models.Index(fields=['provider', 'external_id'], name='user_identi_provide_5ced5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userauthprovider',
            unique_together={('provider', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['user'], name='user_challe_user_id_99d49d_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['challenge'], name='user_challe_challen_e51a3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddIndex(
            model_name='userchallengesubmit',
            index=models.Index(fields=['user'], name='user_challe_user_id_d340bc_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengesubmit',
            index=models.Index(fields=['challenge'], name='user_challe_challen_f6a8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengesubmit',
            index=models.Index(fields=['user', 'challenge'], name='user_challe_user_id_50c93c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['user'], name='user_course_user_id_8166b8_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['course'], name='user_course_course__689467_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user'], name='user_lesson_user_id_5d18f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['lesson'], name='user_lesson_lesson__9d98fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user'], name='user_permis_user_id_281a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission'], name='user_permis_permiss_0999ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_4f95f8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_learning_point'], name='user_profil_total_l_dafbeb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_challenge_point'], name='user_profil_total_c_442daf_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_quiz_point'], name='user_profil_total_q_8a5498_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['quiz'], name='user_quiz_a_quiz_id_fb4f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['user'], name='user_quiz_a_user_id_475532_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['user', 'quiz', '-started_at'], name='user_quiz_a_user_id_6b4270_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizanswer',
            index=models.Index(fields=['attempt'], name='user_quiz_a_attempt_7ee81d_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizanswer',
            index=models.Index(fields=['question'], name='user_quiz_a_questio_74b613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userquizanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='userquizprogress',
            index=models.Index(fields=['user'], name='user_quiz_p_user_id_53c887_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizprogress',
            index=models.Index(fields=['quiz'], name='user_quiz_p_quiz_id_d18407_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userquizprogress',
            unique_together={('user', 'quiz')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='user_role_user_id_d8192c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='user_role_role_id_8c260c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='user_sessio_user_id_c6fc39_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_hash'], name='user_sessio_refresh_90aa65_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['revoked_at'], name='user_sessio_revoked_e5bb87_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='user_sessio_expires_85bda6_idx'),
        ),
    ]
