# Generated by Django 6.0.1 on 2026-03-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['category'], name='system_conf_categor_fa6bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['is_runtime'], name='system_conf_is_runt_f1aa25_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['is_editable'], name='system_conf_is_edit_eb3e35_idx'),
        ),
    ]
