# Generated by Django 6.0 on 2026-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_systemconfig_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
