# Generated by Django 6.0 on 2026-04-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_quiz_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthprovider',
            name='provider',
            field=models.CharField(choices=[('authentik', 'Authentik'), ('google', 'Google'), ('github', 'GitHub')], max_length=50),
        ),
    ]
