# Generated by Django 6.0 on 2026-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userauthprovider_provider_max_length_add_quizquestion_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'status'], name='quiz_questi_quiz_id_9b3ae5_idx'),
        ),
    ]
