# Generated by Django 6.0 on 2026-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_quizquestion_quiz_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='structure_version',
            field=models.IntegerField(db_column='structure_version', default=1, help_text='Increments when course tree/lesson structure changes'),
        ),
    ]
