# Generated by Django 6.0 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_course_progress_cache_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, help_text='Stable deduplication key for auto-generated notifications', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'event_key'), name='uq_notification_user_event_key'),
        ),
    ]