# Generated by Django 6.0 on 2026-05-28 17:34

import django.db.models.deletion
from django.db import migrations, models


def blank_duplicate_emails(apps, schema_editor):
    """Clear duplicate emails so the partial-unique constraint can apply.

    Keeps the earliest occurrence (lowest id) and blanks the rest. Existing dev
    databases may have duplicates from when email had no unique constraint.
    """
    User = apps.get_model('api', 'User')
    seen = set()
    for user in User.objects.exclude(email='').order_by('id').iterator():
        key = (user.email or '').lower()
        if not key:
            continue
        if key in seen:
            user.email = ''
            user.save(update_fields=['email'])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lesson_status_userpermission_createaudit'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='replaced_by',
            field=models.ForeignKey(blank=True, db_column='replaced_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='api.usersession'),
        ),
        migrations.AlterField(
            model_name='challengeflag',
            name='flag_value',
            field=models.TextField(help_text='Plaintext flag value or regex pattern; never returned to client'),
        ),
        migrations.AlterField(
            model_name='challengeinstance',
            name='flag_value',
            field=models.TextField(blank=True, help_text='Plaintext instance-specific flag (set on deploy if random_tail_length > 0)', null=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['replaced_at'], name='user_sessio_replace_1113f2_idx'),
        ),
        migrations.RunPython(blank_duplicate_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('email',), name='uniq_user_email_when_present'),
        ),
    ]
