# Generated by Django 6.0 on 2026-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auth_session_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizconfig',
            name='immediate_feedback',
            field=models.BooleanField(default=True, help_text='Hiện đúng/sai ngay sau mỗi câu; nếu tắt chỉ xem tổng kết cuối'),
        ),
        migrations.AddField(
            model_name='quizconfig',
            name='question_filter',
            field=models.CharField(choices=[('all', 'All questions'), ('unsolved', 'Only not-yet-correct'), ('solved', 'Only already-correct')], default='all', help_text='Lọc câu: tất cả / chỉ câu chưa từng đúng / chỉ câu đã đúng (ôn tập)', max_length=20),
        ),
    ]
