# Generated by Django 6.0 on 2026-06-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_backfill_quiz_point_and_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('filename', models.TextField(help_text='Tên file hiển thị cho người dùng')),
                ('storage_key', models.TextField(help_text='Đường dẫn tương đối dưới MEDIA_ROOT (challenges/<slug>/<filename>)')),
                ('size', models.BigIntegerField(default=0, help_text='Kích thước file (bytes)')),
                ('content_type', models.TextField(blank=True, help_text='MIME type suy ra từ filename', null=True)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('gitlab', 'GitLab')], default='upload', max_length=20)),
                ('gitlab_path', models.TextField(blank=True, help_text='Đường dẫn file trong repo GitLab (nếu source là gitlab)', null=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.challenge')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_file',
                'indexes': [models.Index(fields=['challenge'], name='challenge_f_challen_e134b1_idx')],
            },
        ),
    ]
