# Generated by Django 6.0 on 2026-06-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_challengefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='deploy_source_ref',
            field=models.TextField(blank=True, help_text='Image ref để deploy instance (vd registry.gitlab.example/grp/chal:latest). Khi tạo challenge từ GitLab, form prefill từ gitlab_path; admin sửa được. Deploy server pull image này. Rỗng = challenge chưa cấu hình deploy.', null=True),
        ),
    ]
