BUILTIN_ROLE_ADMIN = 'Admin'
BUILTIN_ROLE_EDITOR = 'Editor'
BUILTIN_ROLE_MEMBER = 'Member'

BUILTIN_ROLES = (
    BUILTIN_ROLE_ADMIN,
    BUILTIN_ROLE_EDITOR,
    BUILTIN_ROLE_MEMBER,
)

LOGIN_FAIL_CACHE_KEY_TEMPLATE = 'login_fail:{username}'
REFRESH_RATE_CACHE_KEY_TEMPLATE = 'refresh_rate:{user_id}'

DEFAULT_LOGIN_MAX_FAILURES = 5
DEFAULT_LOGIN_FAILURE_TTL_SECONDS = 300
DEFAULT_REFRESH_RATE_LIMIT_PER_MINUTE = 10
DEFAULT_REFRESH_RATE_LIMIT_WINDOW_SECONDS = 60

REFRESH_TTL_CONFIG_KEY = 'auth.token.refresh_ttl'
DEFAULT_REFRESH_TTL_MINUTES = 60 * 24 * 7
